# Site settings
title: "TACOS 2020"
email: tacos2020@linguistik.computer
url: https://2020.linguistik.computer
description: "19. – 21. June 2020 in Heidelberg"

en:
  title: "TACOS 2020"
  description: "19th – 21st June 2020 in Heidelberg"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-fg: '#000000'
  primary-bg: '#f4f1ea'
  links: '#800000'

# Footer settings
footer: TaCoS Koordination

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/fscolihd
  - title: facebook
    url:

# Build settings
markdown: kramdown
permalink: pretty
