# Site settings
title: TACOS 2020
email: tacos2020@linguistik.computer
url: https://2020.linguistik.computer
description: "19. – 21. Jun. 2020 in Heidelberg"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#6D214F'
  links: 'FFFFFF'

# Footer settings
footer: TaCoS 2020 Koordination

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/fscolihd
  - title: facebook
    url:

# Build settings
markdown: kramdown
permalink: pretty
